services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    user: root
    restart: "no"
    environment:
      - _JAVA_OPTIONS=-Xmx1G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
      - lavalink_plugins:/opt/Lavalink/plugins
    networks:
      - lavalink-network

  bot:
    build: .
    container_name: annie-cansada-bot
    restart: "no"
    depends_on:
      - lavalink
    env_file:
      - .env
    environment:
      - LAVALINK_HOST=lavalink
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - lavalink-network

volumes:
  lavalink_plugins:

networks:
  lavalink-network:
    driver: bridge